#!/bin/zsh

if [ -d ~/Library/Application\ Support/Infineon_Technologies_AG ] ; then
    echo -n "Removing Infineon-Toolbox Tools files..."
    rm -rf ~/Library/Application\ Support/Infineon_Technologies_AG
    echo " done."
fi

if [ -d ~/Library/Application\ Support/Infineon\ Developer\ Center\ Launcher ] ; then
    echo -n "Removing Infineon-Toolbox Tools files..."
    rm -rf ~/Library/Application\ Support/Infineon\ Developer\ Center\ Launcher
    echo " done."
fi

if [ -d ~/Library/Infineon ] ; then
    echo -n "Removing Infineon-Toolbox Tools files..."
    rm -rf ~/Library/Infineon
    echo " done."
fi

if [ -d ~/Applications ]; then
    echo -n "Removing Infineon-Toolbox application..."
    rm -rf ~/Applications
    echo " done."
fi

if [ -d /Library/Infineon ]; then
    echo -n "Removing Infineon Launcher Services..."
    sudo rm -rf /Library/Infineon
    echo " done."
fi

if [ -d /Library/Application\ Support/Infineon_Technologies_AG ]; then
    echo -n "Removing Infineon Application Support files..."
    sudo rm -rf /Library/Application\ Support/Infineon_Technologies_AG
    echo " done."
fi

rm -rf /Applications/Modus*
rm -rf /Applications/dashboard.app
rm -rf /Applications/dfuh-tool.app
rm -rf /Applications/bsp-assistant.app
rm -rf /Applications/mtb-gcc-arm-eabi
rm -rf /Applications/project-creator.app
rm -rf /Applications/secure-policy-configurator
rm -rf /Applications/Infineon*
